export const UPDATE_ENTRY_TAGS = 'UPDATE_ENTRY_TAGS';
export const UPDATE_ENTRY_BODY = 'UPDATE_ENTRY_BODY';
export const UPDATE_TAGS = 'UPDATE_TAGS';
export const TOGGLE_CALENDAR_VISIBILITY = 'TOGGLE_CALENDAR_VISIBILITY';
